-- ProbashOS initial schema (§45). Explicit SQL, no ORM-generated migrations (§83).
-- UUIDv7 values are generated by the application so ids stay time-sortable (§42.6).
-- Money is stored as (minor_units BIGINT, currency CHAR(3)) — never as a float (§83).

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migration (
  filename    TEXT PRIMARY KEY,
  applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- identity ---
CREATE TABLE app_user (
  id                          UUID PRIMARY KEY,
  phone_e164                  TEXT NOT NULL UNIQUE,
  display_name                TEXT,
  roles                       TEXT[] NOT NULL DEFAULT '{}',
  locale                      TEXT NOT NULL DEFAULT 'bn-BD',
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at                TIMESTAMPTZ,
  created_by_assistant_user_id UUID REFERENCES app_user (id)
);

CREATE TABLE otp_challenge (
  id                   UUID PRIMARY KEY,
  phone_e164           TEXT NOT NULL,
  code_hash            TEXT NOT NULL,
  expires_at           TIMESTAMPTZ NOT NULL,
  attempts             INT NOT NULL DEFAULT 0,
  consumed_at          TIMESTAMPTZ,
  locale               TEXT NOT NULL DEFAULT 'bn-BD',
  assisted_by_user_id  UUID REFERENCES app_user (id)
);
CREATE INDEX otp_challenge_phone_idx ON otp_challenge (phone_e164, expires_at DESC);

CREATE TABLE user_session (
  id          UUID PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  token_hash  TEXT NOT NULL UNIQUE,
  kind        TEXT NOT NULL CHECK (kind IN ('self', 'assisted', 'delegated', 'break_glass')),
  issued_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked_at  TIMESTAMPTZ
);

CREATE TABLE identity_profile (
  id                      UUID PRIMARY KEY,
  user_id                 UUID NOT NULL UNIQUE REFERENCES app_user (id) ON DELETE CASCADE,
  intent                  TEXT NOT NULL DEFAULT 'work' CHECK (intent IN ('work', 'study')),
  display_name            TEXT,
  occupation_key          TEXT,
  experience_months       INT,
  education_level         TEXT,
  has_valid_passport      BOOLEAN,
  passport_valid_months   INT,
  has_bmet_registration   BOOLEAN,
  has_police_clearance    BOOLEAN,
  language_certificates   TEXT[] NOT NULL DEFAULT '{}',
  skill_certificates      TEXT[] NOT NULL DEFAULT '{}',
  medically_fit           BOOLEAN,
  destination_preferences TEXT[] NOT NULL DEFAULT '{}',
  district                TEXT,
  age_years               INT,
  locale                  TEXT NOT NULL DEFAULT 'bn-BD',
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- §50: national identifiers are field-level encrypted; the plaintext never lands here.
  nid_ciphertext          BYTEA,
  passport_no_ciphertext  BYTEA
);

CREATE TABLE consent (
  id                   UUID PRIMARY KEY,
  user_id              UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  purpose              TEXT NOT NULL,
  granted              BOOLEAN NOT NULL,
  statement_bn         TEXT NOT NULL,
  statement_en         TEXT NOT NULL,
  locale               TEXT NOT NULL,
  granted_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at           TIMESTAMPTZ,
  captured_by_user_id  UUID REFERENCES app_user (id),
  evidence_kind        TEXT,
  evidence_reference   TEXT
);

CREATE TABLE delegation (
  id                 UUID PRIMARY KEY,
  principal_user_id  UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  delegate_user_id   UUID REFERENCES app_user (id),
  delegate_phone     TEXT NOT NULL,
  delegate_name      TEXT,
  relationship       TEXT NOT NULL,
  permissions        TEXT[] NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('invited', 'active', 'revoked', 'expired')),
  invited_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at        TIMESTAMPTZ,
  revoked_at         TIMESTAMPTZ,
  expires_at         TIMESTAMPTZ,
  consent_id         UUID NOT NULL REFERENCES consent (id)
);

-- ----------------------------------------------------------- organizations ---
CREATE TABLE organization (
  id                   UUID PRIMARY KEY,
  type                 TEXT NOT NULL,
  legal_name_bn        TEXT NOT NULL,
  legal_name_en        TEXT NOT NULL,
  country_code         CHAR(2) NOT NULL,
  registration_number  TEXT,
  official_domain      TEXT,
  verification_level   TEXT NOT NULL DEFAULT 'unverified',
  verification         JSONB NOT NULL DEFAULT '{}'::jsonb,
  suspended_at         TIMESTAMPTZ,
  suspension_reason    JSONB,
  is_synthetic_demo    BOOLEAN NOT NULL DEFAULT false,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE organization_licence (
  id                UUID PRIMARY KEY,
  organization_id   UUID NOT NULL REFERENCES organization (id) ON DELETE CASCADE,
  number            TEXT NOT NULL,
  authority_bn      TEXT NOT NULL,
  authority_en      TEXT NOT NULL,
  country_code      CHAR(2) NOT NULL,
  status            TEXT NOT NULL,
  valid_from        DATE,
  valid_to          DATE,
  source_id         TEXT,
  last_verified_at  TIMESTAMPTZ
);
CREATE INDEX organization_licence_org_idx ON organization_licence (organization_id);

-- ------------------------------------------------------------- regulations ---
CREATE TABLE country (
  code                 CHAR(2) PRIMARY KEY,
  name_bn              TEXT NOT NULL,
  name_en              TEXT NOT NULL,
  support_status       TEXT NOT NULL,
  work_priority_tier   TEXT NOT NULL,
  is_study_priority    BOOLEAN NOT NULL DEFAULT false,
  status_notice        JSONB,
  status_updated_at    TIMESTAMPTZ
);

CREATE TABLE regulatory_source (
  id                   TEXT PRIMARY KEY,
  kind                 TEXT NOT NULL,
  country_code         CHAR(2) NOT NULL REFERENCES country (code),
  authority            JSONB NOT NULL,
  title                JSONB NOT NULL,
  url                  TEXT NOT NULL,
  review_cadence_days  INT NOT NULL,
  last_retrieved_at    TIMESTAMPTZ,
  last_reviewed_at     TIMESTAMPTZ,
  last_snapshot_hash   TEXT
);

-- Immutable evidence of what we read and when (§42.15).
CREATE TABLE source_snapshot (
  id            UUID PRIMARY KEY,
  source_id     TEXT NOT NULL REFERENCES regulatory_source (id),
  retrieved_at  TIMESTAMPTZ NOT NULL,
  sha256        TEXT NOT NULL,
  storage_key   TEXT NOT NULL,
  content_type  TEXT NOT NULL
);
CREATE INDEX source_snapshot_source_idx ON source_snapshot (source_id, retrieved_at DESC);

CREATE TABLE rule_version (
  id                   TEXT PRIMARY KEY,
  rule_id              TEXT NOT NULL,
  version              INT NOT NULL,
  title                JSONB NOT NULL,
  expression           JSONB NOT NULL,
  source_ids           TEXT[] NOT NULL DEFAULT '{}',
  effective_from       TIMESTAMPTZ NOT NULL,
  effective_to         TIMESTAMPTZ,
  publication_status   TEXT NOT NULL CHECK (publication_status IN ('draft','review','published','withdrawn')),
  verified_at          TIMESTAMPTZ,
  verified_by          TEXT,
  review_cadence_days  INT NOT NULL DEFAULT 7,
  last_reviewed_at     TIMESTAMPTZ,
  UNIQUE (rule_id, version)
);

CREATE TABLE route_version (
  id                     TEXT PRIMARY KEY,
  route_id               TEXT NOT NULL,
  version                INT NOT NULL,
  purpose                TEXT NOT NULL,
  origin_country         CHAR(2) NOT NULL DEFAULT 'BD',
  destination_country    CHAR(2) NOT NULL REFERENCES country (code),
  visa_class             TEXT,
  permit_class           TEXT,
  official_name          JSONB NOT NULL,
  summary                JSONB NOT NULL,
  status                 TEXT NOT NULL,
  eligibility_rule_id    TEXT NOT NULL,
  requirements           JSONB NOT NULL DEFAULT '[]'::jsonb,
  post_arrival           JSONB NOT NULL DEFAULT '[]'::jsonb,
  risk_notices           JSONB NOT NULL DEFAULT '[]'::jsonb,
  expected_timeline      JSONB,
  fee_rule_ids           TEXT[] NOT NULL DEFAULT '{}',
  source_ids             TEXT[] NOT NULL DEFAULT '{}',
  effective_from         TIMESTAMPTZ NOT NULL,
  effective_to           TIMESTAMPTZ,
  verified_at            TIMESTAMPTZ NOT NULL,
  verified_by            TEXT NOT NULL,
  publication_status     TEXT NOT NULL CHECK (publication_status IN ('draft','review','published','withdrawn')),
  review_cadence_days    INT NOT NULL,
  last_reviewed_at       TIMESTAMPTZ,
  is_synthetic_demo      BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (route_id, version)
);
CREATE INDEX route_version_country_idx ON route_version (destination_country, publication_status);

CREATE TABLE fee_rule (
  id                      TEXT PRIMARY KEY,
  route_id                TEXT NOT NULL,
  category                TEXT NOT NULL,
  label                   JSONB NOT NULL,
  amount_minor_units      BIGINT NOT NULL,
  currency                CHAR(3) NOT NULL,
  payer_kind              TEXT NOT NULL,
  payee_kind              TEXT NOT NULL,
  payee_organization_id   UUID REFERENCES organization (id),
  legally_allowed         BOOLEAN,
  legal_basis_source_id   TEXT REFERENCES regulatory_source (id),
  refundable              BOOLEAN NOT NULL,
  mandatory               BOOLEAN NOT NULL,
  receipt_required        BOOLEAN NOT NULL,
  milestone_key           TEXT,
  source_ids              TEXT[] NOT NULL DEFAULT '{}',
  effective_from          TIMESTAMPTZ NOT NULL,
  effective_to            TIMESTAMPTZ,
  unresolved              BOOLEAN NOT NULL DEFAULT false
);

-- -------------------------------------------------------------------- work ---
CREATE TABLE occupation (
  id           TEXT PRIMARY KEY,
  key          TEXT NOT NULL UNIQUE,
  family       TEXT NOT NULL,
  title        JSONB NOT NULL,
  isco_code    CHAR(4) NOT NULL,
  skill_level  SMALLINT NOT NULL CHECK (skill_level BETWEEN 1 AND 4)
);

CREATE TABLE occupation_code_mapping (
  id              UUID PRIMARY KEY,
  occupation_id   TEXT NOT NULL REFERENCES occupation (id) ON DELETE CASCADE,
  classification  TEXT NOT NULL,
  code            TEXT NOT NULL,
  country_code    CHAR(2),
  source_id       TEXT REFERENCES regulatory_source (id),
  last_verified_at TIMESTAMPTZ
);

CREATE TABLE job (
  id                          UUID PRIMARY KEY,
  public_id                   TEXT NOT NULL UNIQUE,
  route_version_id            TEXT NOT NULL REFERENCES route_version (id),
  destination_country         CHAR(2) NOT NULL REFERENCES country (code),
  occupation_id               TEXT NOT NULL REFERENCES occupation (id),
  title                       JSONB NOT NULL,
  description                 JSONB NOT NULL,
  employer_organization_id    UUID NOT NULL REFERENCES organization (id),
  recruiter_organization_id   UUID REFERENCES organization (id),
  positions                   INT NOT NULL CHECK (positions > 0),
  terms                       JSONB NOT NULL,
  allowed_worker_cost_minor   BIGINT NOT NULL,
  allowed_worker_cost_ccy     CHAR(3) NOT NULL,
  verification                JSONB NOT NULL,
  publication_status          TEXT NOT NULL,
  demand_valid_from           TIMESTAMPTZ NOT NULL,
  demand_valid_to             TIMESTAMPTZ NOT NULL,
  is_synthetic_demo           BOOLEAN NOT NULL DEFAULT false,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX job_public_idx ON job (publication_status, destination_country);

-- ------------------------------------------------------------ applications ---
CREATE TABLE mobility_case (
  id                   UUID PRIMARY KEY,
  owner_user_id        UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  purpose              TEXT NOT NULL CHECK (purpose IN ('work', 'study')),
  state                TEXT NOT NULL,
  route_version_id     TEXT NOT NULL REFERENCES route_version (id),
  job_id               UUID REFERENCES job (id),
  destination_country  CHAR(2) NOT NULL REFERENCES country (code),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX mobility_case_owner_idx ON mobility_case (owner_user_id, updated_at DESC);

CREATE TABLE case_state_change (
  id           UUID PRIMARY KEY,
  case_id      UUID NOT NULL REFERENCES mobility_case (id) ON DELETE CASCADE,
  from_state   TEXT NOT NULL,
  to_state     TEXT NOT NULL,
  actor_user_id UUID REFERENCES app_user (id),
  reason       TEXT,
  occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE case_task (
  id                UUID PRIMARY KEY,
  case_id           UUID NOT NULL REFERENCES mobility_case (id) ON DELETE CASCADE,
  ordinal           INT NOT NULL,
  title             JSONB NOT NULL,
  why_needed        JSONB NOT NULL,
  owner             TEXT NOT NULL,
  mandatory         BOOLEAN NOT NULL,
  status            TEXT NOT NULL,
  depends_on        UUID[] NOT NULL DEFAULT '{}',
  estimated_days    INT,
  performed_at      JSONB,
  source_ids        TEXT[] NOT NULL DEFAULT '{}',
  listen_key        TEXT,
  due_at            TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ
);
CREATE INDEX case_task_case_idx ON case_task (case_id, ordinal);

CREATE TABLE case_milestone (
  id                UUID PRIMARY KEY,
  case_id           UUID NOT NULL REFERENCES mobility_case (id) ON DELETE CASCADE,
  key               TEXT NOT NULL,
  label             JSONB NOT NULL,
  status            TEXT NOT NULL,
  attestable_by     TEXT[] NOT NULL DEFAULT '{}',
  evidence_document_ids UUID[] NOT NULL DEFAULT '{}',
  verified_at       TIMESTAMPTZ,
  verified_by       TEXT,
  failure_reason    JSONB,
  UNIQUE (case_id, key)
);

-- --------------------------------------------------------------- documents ---
CREATE TABLE document (
  id                   UUID PRIMARY KEY,
  owner_user_id        UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  case_id              UUID REFERENCES mobility_case (id),
  type                 TEXT NOT NULL,
  label                JSONB NOT NULL,
  storage_key          TEXT NOT NULL,
  content_type         TEXT NOT NULL,
  byte_size            BIGINT NOT NULL,
  sha256               TEXT NOT NULL,
  version              INT NOT NULL DEFAULT 1,
  uploaded_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  issued_at            DATE,
  expires_at           DATE,
  issuer               JSONB,
  verification_level   TEXT NOT NULL DEFAULT 'unverified',
  verified_at          TIMESTAMPTZ,
  malware_scan_status  TEXT NOT NULL DEFAULT 'pending'
);
CREATE INDEX document_owner_idx ON document (owner_user_id, uploaded_at DESC);
CREATE INDEX document_expiry_idx ON document (expires_at) WHERE expires_at IS NOT NULL;

CREATE TABLE document_share (
  id                  UUID PRIMARY KEY,
  document_id         UUID NOT NULL REFERENCES document (id) ON DELETE CASCADE,
  granted_by_user_id  UUID NOT NULL REFERENCES app_user (id),
  audience_kind       TEXT NOT NULL,
  audience_id         TEXT,
  purpose             JSONB NOT NULL,
  expires_at          TIMESTAMPTZ NOT NULL,
  revoked_at          TIMESTAMPTZ,
  watermark           BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  access_count        INT NOT NULL DEFAULT 0
);

-- ------------------------------------------------------------ cost/payment ---
CREATE TABLE cost_plan (
  id                UUID PRIMARY KEY,
  case_id           UUID NOT NULL REFERENCES mobility_case (id) ON DELETE CASCADE,
  primary_currency  CHAR(3) NOT NULL,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_ids        TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE cost_item (
  id                     UUID PRIMARY KEY,
  cost_plan_id           UUID NOT NULL REFERENCES cost_plan (id) ON DELETE CASCADE,
  case_id                UUID NOT NULL REFERENCES mobility_case (id) ON DELETE CASCADE,
  category               TEXT NOT NULL,
  label                  JSONB NOT NULL,
  amount_minor_units     BIGINT NOT NULL,
  currency               CHAR(3) NOT NULL,
  payer_kind             TEXT NOT NULL,
  payer_id               TEXT,
  payee_kind             TEXT NOT NULL,
  payee_id               TEXT,
  legally_allowed        BOOLEAN,
  legal_basis_source_id  TEXT REFERENCES regulatory_source (id),
  refundable             BOOLEAN NOT NULL,
  mandatory              BOOLEAN NOT NULL,
  receipt_required       BOOLEAN NOT NULL,
  milestone_key          TEXT,
  status                 TEXT NOT NULL,
  source_ids             TEXT[] NOT NULL DEFAULT '{}',
  unresolved             BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX cost_item_case_idx ON cost_item (case_id);

CREATE TABLE payment_intent (
  id                  UUID PRIMARY KEY,
  case_id             UUID NOT NULL REFERENCES mobility_case (id),
  cost_item_id        UUID NOT NULL REFERENCES cost_item (id),
  user_id             UUID NOT NULL REFERENCES app_user (id),
  amount_minor_units  BIGINT NOT NULL,
  currency            CHAR(3) NOT NULL,
  payee_kind          TEXT NOT NULL,
  payee_id            TEXT NOT NULL,
  method              TEXT NOT NULL,
  provider            TEXT NOT NULL,
  status              TEXT NOT NULL,
  milestone_key       TEXT,
  idempotency_key     TEXT NOT NULL UNIQUE,
  provider_reference  TEXT,
  is_sandbox          BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmed_at        TIMESTAMPTZ
);

CREATE TABLE provider_transaction (
  id                  UUID PRIMARY KEY,
  payment_intent_id   UUID NOT NULL REFERENCES payment_intent (id),
  provider            TEXT NOT NULL,
  event               TEXT NOT NULL,
  amount_minor_units  BIGINT NOT NULL,
  currency            CHAR(3) NOT NULL,
  occurred_at         TIMESTAMPTZ NOT NULL,
  received_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  idempotency_key     TEXT NOT NULL UNIQUE
);

CREATE TABLE ledger_account (
  id           UUID PRIMARY KEY,
  code         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  type         TEXT NOT NULL CHECK (type IN ('asset','liability','equity','income','expense')),
  currency     CHAR(3) NOT NULL,
  owner_kind   TEXT,
  owner_id     TEXT,
  opened_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at    TIMESTAMPTZ
);

CREATE TABLE journal_entry (
  id                 UUID PRIMARY KEY,
  reference          TEXT NOT NULL,
  description        TEXT NOT NULL,
  occurred_at        TIMESTAMPTZ NOT NULL,
  recorded_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  idempotency_key    TEXT NOT NULL UNIQUE,
  reverses_entry_id  UUID REFERENCES journal_entry (id),
  metadata           JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE journal_line (
  id                  UUID PRIMARY KEY,
  entry_id            UUID NOT NULL REFERENCES journal_entry (id) ON DELETE RESTRICT,
  account_code        TEXT NOT NULL REFERENCES ledger_account (code),
  direction           TEXT NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount_minor_units  BIGINT NOT NULL CHECK (amount_minor_units > 0),
  currency            CHAR(3) NOT NULL,
  memo                TEXT
);
CREATE INDEX journal_line_account_idx ON journal_line (account_code);

-- Journal entries are immutable: corrections are new reversing entries (ADR 0004).
CREATE RULE journal_entry_no_update AS ON UPDATE TO journal_entry DO INSTEAD NOTHING;
CREATE RULE journal_entry_no_delete AS ON DELETE TO journal_entry DO INSTEAD NOTHING;
CREATE RULE journal_line_no_update AS ON UPDATE TO journal_line DO INSTEAD NOTHING;
CREATE RULE journal_line_no_delete AS ON DELETE TO journal_line DO INSTEAD NOTHING;

-- ------------------------------------------------------------------ safety ---
CREATE TABLE offer_scan (
  id                     UUID PRIMARY KEY,
  user_id                UUID REFERENCES app_user (id),
  verdict                TEXT NOT NULL,
  signals                JSONB NOT NULL DEFAULT '[]'::jsonb,
  checks_performed       JSONB NOT NULL DEFAULT '[]'::jsonb,
  matched_job_public_id  TEXT,
  human_review_requested BOOLEAN NOT NULL DEFAULT false,
  input_digest           TEXT NOT NULL,
  scanned_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE complaint (
  id              UUID PRIMARY KEY,
  case_id         UUID REFERENCES mobility_case (id),
  raised_by_user_id UUID REFERENCES app_user (id),
  against_organization_id UUID REFERENCES organization (id),
  category        TEXT NOT NULL,
  body            TEXT NOT NULL,
  status          TEXT NOT NULL,
  opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ
);
-- §76.8 — a complaint can never be deleted, including by the organization complained about.
CREATE RULE complaint_no_delete AS ON DELETE TO complaint DO INSTEAD NOTHING;

-- ------------------------------------------------------------------- audit ---
CREATE TABLE audit_event (
  id             UUID PRIMARY KEY,
  kind           TEXT NOT NULL CHECK (kind IN ('action', 'access', 'security')),
  actor_user_id  UUID REFERENCES app_user (id),
  action         TEXT NOT NULL,
  resource_type  TEXT NOT NULL,
  resource_id    TEXT,
  case_id        UUID REFERENCES mobility_case (id),
  reason         TEXT,
  occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX audit_event_actor_idx ON audit_event (actor_user_id, occurred_at DESC);
CREATE INDEX audit_event_resource_idx ON audit_event (resource_type, resource_id);
CREATE RULE audit_event_no_update AS ON UPDATE TO audit_event DO INSTEAD NOTHING;
CREATE RULE audit_event_no_delete AS ON DELETE TO audit_event DO INSTEAD NOTHING;

-- §47 — transactional outbox for reliable event publication.
CREATE TABLE outbox_event (
  id            UUID PRIMARY KEY,
  event_name    TEXT NOT NULL,
  payload       JSONB NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at  TIMESTAMPTZ
);
CREATE INDEX outbox_unpublished_idx ON outbox_event (created_at) WHERE published_at IS NULL;

INSERT INTO schema_migration (filename) VALUES ('0001_init.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
